cc_library(
    name = "cpp_ethereum_lib",
    srcs = glob(["lib/boost/*.a", "lib/**/*.a"]),
    hdrs = glob(["include/**/*.hpp", "include/**/*.h", "include/**/*.ipp"]),
    includes =["include"],
    visibility = ["//visibility:public"],
    linkstatic = 1,
    linkopts = ["-lstdc++", "-ldl", "-pthread"],
    deps = [
        "@leveldb_git//:leveldb",
        "//external:cryptopp",
        "//external:ethash",
        "//external:libdevcore",
        "//external:libdevcrypto",
        #"//external:leveldb",
        "@boost//:log",
        "@boost//:detail",
        "@boost//:system",
        "@boost//:filesystem",
        "@boost//:program_options",
        "@boost//:multiprecision",
    ],
    alwayslink = 1,
)
